"use client";

import { useEffect, useRef } from "react";
import { ImageUpload } from "../../media/image-upload";
import type { ContentBlock, EditorEntity, StructuredBody } from "../types";

export function BlockEditor({ value, onChange, entities = [], disabled = false }: { value: StructuredBody; onChange: (body: StructuredBody) => void; entities?: EditorEntity[]; disabled?: boolean }) {
  const root = useRef<HTMLDivElement>(null);
  const latestBody = useRef(value);
  useEffect(() => { latestBody.current = value; }, [value]);
  function replace(index: number, block: ContentBlock) { onChange({ ...value, blocks: value.blocks.map((current, position) => position === index ? block : current) }); }
  function move(index: number, offset: number) { const blocks = [...value.blocks]; [blocks[index], blocks[index + offset]] = [blocks[index + offset], blocks[index]]; onChange({ ...value, blocks }); requestAnimationFrame(() => root.current?.querySelectorAll<HTMLElement>(".block-item")[index + offset]?.focus()); }
  function remove(index: number) { onChange({ ...value, blocks: value.blocks.filter((_, position) => position !== index) }); requestAnimationFrame(() => (root.current?.querySelectorAll<HTMLElement>(".block-item")[Math.max(0, index - 1)] ?? root.current?.querySelector<HTMLElement>(".block-add button"))?.focus()); }
  function add(block: ContentBlock) { const current = latestBody.current; if (current.blocks.length >= 150) return; onChange({ ...current, blocks: [...current.blocks, block] }); requestAnimationFrame(() => root.current?.querySelectorAll<HTMLElement>(".block-item")[current.blocks.length]?.focus()); }
  return <div className="block-editor" ref={root}><p className="editor-hint">分段写作，可插入小标题、引文和相关校园档案。</p>{value.blocks.map((block, index) => <section tabIndex={-1} className="block-item" key={index} aria-label={`第 ${index + 1} 段`}>
    <div className="block-tools"><span>{index + 1} / {block.type === "entity" ? "档案引用" : block.type === "image" ? "图片" : "正文"}</span><div><button type="button" disabled={disabled || index === 0} onClick={() => move(index, -1)} aria-label={`上移第 ${index + 1} 段`}>↑</button><button type="button" disabled={disabled || index === value.blocks.length - 1} onClick={() => move(index, 1)} aria-label={`下移第 ${index + 1} 段`}>↓</button><button type="button" disabled={disabled} onClick={() => remove(index)} aria-label={`删除第 ${index + 1} 段`}>删除</button></div></div>
    {"text" in block ? <><label>段落样式<select disabled={disabled} value={block.type} onChange={(event) => replace(index, { type: event.target.value as "paragraph" | "heading" | "quote", text: block.text })}><option value="paragraph">正文</option><option value="heading">小标题</option><option value="quote">引文</option></select></label><label className="sr-only" htmlFor={`block-text-${index}`}>第 {index + 1} 段内容</label><textarea id={`block-text-${index}`} disabled={disabled} rows={block.type === "heading" ? 2 : 5} maxLength={20000} value={block.text} onChange={(event) => replace(index, { ...block, text: event.target.value })} /></> : block.type === "entity" ? <label>相关档案<select disabled={disabled} value={`${block.entity_type}:${block.entity_id}`} onChange={(event) => { const entity = entities.find((item) => `${item.type}:${item.id}` === event.target.value); if (entity) replace(index, { type: "entity", entity_type: entity.type, entity_id: entity.id, label: entity.label }); }}><option value={`${block.entity_type}:${block.entity_id}`}>{block.label}</option>{entities.filter((item) => item.id !== block.entity_id).map((item) => <option key={`${item.type}:${item.id}`} value={`${item.type}:${item.id}`}>{item.label} · {item.type === "student" ? "人物" : item.type === "college" ? "学院" : item.type === "place" ? "地点" : "事件"}</option>)}</select></label> : <label>图片说明<input disabled={disabled} value={block.alt} maxLength={300} onChange={(event) => replace(index, { ...block, alt: event.target.value })} /></label>}
  </section>)}<div className="block-add"><button type="button" disabled={disabled || value.blocks.length >= 150} onClick={() => add({ type: "paragraph", text: "" })}>＋ 添加段落</button><button type="button" disabled={disabled || !entities.length || value.blocks.length >= 150} onClick={() => { const entity = entities[0]; if (entity) add({ type: "entity", entity_type: entity.type, entity_id: entity.id, label: entity.label }); }}>＋ 引用档案</button></div><ImageUpload disabled={disabled || value.blocks.length >= 150} onUploaded={(asset) => add({ type: "image", asset_id: asset.id, alt: "" })} /></div>;
}

