"use client";
import { useActionState, useState, useRef, startTransition, type FormEvent } from "react";
import { MarkdownImport } from "../../import/markdown-import";
import Link from "next/link";
import { GuideLink } from "../../guide/guide-link";
import { saveEvent } from "../actions";
import type { EventNode, EventRecord } from "../queries";
import type { WikiEntitySummary } from "../../wiki/types";

type NodeInput = Pick<EventNode, "id" | "label" | "title" | "description">;
export function EventForm({ event, initialNodes = [], initialLinks = [], entities, saved = false }: { event?: EventRecord; initialNodes?: NodeInput[]; initialLinks?: { entity_type: string; entity_id: string }[]; entities: WikiEntitySummary[]; saved?: boolean }) {
  const [fields, setFields] = useState({ title: event?.title ?? "", summary: event?.summary ?? "", time_range: event?.time_range ?? "", starts_on: event?.starts_on ?? "", ends_on: event?.ends_on ?? "", causes: event?.causes ?? "", consequences: event?.consequences ?? "" });
  const [imported, setImported] = useState(false);
  const intentRef = useRef<HTMLInputElement>(null);
  const [state, action, pending] = useActionState(saveEvent, { error: null });
  const [nodes, setNodes] = useState<NodeInput[]>(initialNodes);
  const [links, setLinks] = useState(initialLinks.map((link) => `${link.entity_type}:${link.entity_id}`));
  const [preview, setPreview] = useState(false);
  function updateNode(id: string, key: "label" | "title" | "description", value: string) { setNodes(nodes.map((node) => node.id === id ? { ...node, [key]: value } : node)); }
  function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const data = new FormData(event.currentTarget); startTransition(() => action(data)); }
  return <form action={action} onSubmit={submit} className="event-form">
    {event?.status !== "published" && <MarkdownImport kind="event" disabled={pending} onImport={data => { setFields(data); setNodes(data.nodes.map(node => ({ ...node, id: crypto.randomUUID() }))); setPreview(false); setImported(true); }} />}
    <GuideLink section="events">查看事件档案与补充材料教程</GuideLink>
    <input type="hidden" name="intent" defaultValue="save" ref={intentRef} /><input type="hidden" name="id" value={event?.id ?? ""} /><input type="hidden" name="version" value={event?.version ?? ""} />
    <input type="hidden" name="nodes" value={JSON.stringify(nodes)} /><input type="hidden" name="links" value={JSON.stringify(links.map((value) => { const [entity_type, entity_id] = value.split(":"); return { entity_type, entity_id }; }))} />
    {state.error && <p className="event-alert" role="alert">{state.error}</p>}{saved && !imported && !state.error && <p className="event-notice" role="status">已保存。可以继续编辑或预览。</p>}
    <fieldset disabled={pending}><legend>主档案</legend><label>档案标题<input name="title" value={fields.title} onChange={e => setFields(current => ({ ...current, title: e.target.value }))} required maxLength={160} /></label><label>概述<textarea name="summary" value={fields.summary} onChange={e => setFields(current => ({ ...current, summary: e.target.value }))} rows={4} maxLength={2000} /></label><label>时间说明<input name="time_range" value={fields.time_range} onChange={e => setFields(current => ({ ...current, time_range: e.target.value }))} maxLength={160} placeholder="例如：某学年秋季学期" /></label><div className="event-form-pair"><label>开始日期（可选）<input type="date" name="starts_on" value={fields.starts_on} onChange={e => setFields(current => ({ ...current, starts_on: e.target.value }))} /></label><label>结束日期（可选）<input type="date" name="ends_on" value={fields.ends_on} onChange={e => setFields(current => ({ ...current, ends_on: e.target.value }))} /></label></div><label>事件背景<textarea name="causes" value={fields.causes} onChange={e => setFields(current => ({ ...current, causes: e.target.value }))} rows={5} maxLength={10000} /></label><label>后续影响<textarea name="consequences" value={fields.consequences} onChange={e => setFields(current => ({ ...current, consequences: e.target.value }))} rows={5} maxLength={10000} /></label></fieldset>
    <fieldset disabled={pending}><legend>时间线</legend><p>按事件发生顺序编排。已有补充材料引用的节点需保留。</p>{nodes.map((node, index) => <section className="event-node-editor" key={node.id}><div className="event-form-pair"><label>时间标记<input value={node.label ?? ""} onChange={(e) => updateNode(node.id, "label", e.target.value)} maxLength={120} /></label><label>节点标题<input value={node.title} onChange={(e) => updateNode(node.id, "title", e.target.value)} required maxLength={160} /></label></div><label>经过<textarea value={node.description ?? ""} onChange={(e) => updateNode(node.id, "description", e.target.value)} rows={4} maxLength={10000} /></label><div className="event-actions"><button type="button" disabled={index === 0} onClick={() => { const next = [...nodes]; [next[index - 1], next[index]] = [next[index], next[index - 1]]; setNodes(next); }}>上移</button><button type="button" disabled={index === nodes.length - 1} onClick={() => { const next = [...nodes]; [next[index + 1], next[index]] = [next[index], next[index + 1]]; setNodes(next); }}>下移</button><button type="button" onClick={() => setNodes(nodes.filter((value) => value.id !== node.id))}>移除节点</button></div></section>)}<button type="button" onClick={() => setNodes([...nodes, { id: crypto.randomUUID(), label: "", title: "", description: "" }])}>＋ 添加时间节点</button></fieldset>
    <fieldset disabled={pending}><legend>关联人物、学院与地点</legend>{entities.length ? <div className="event-entity-options">{entities.map((entity) => { const value = `${entity.type}:${entity.id}`; return <label key={value}><input type="checkbox" checked={links.includes(value)} onChange={(e) => setLinks(e.target.checked ? [...links, value] : links.filter((item) => item !== value))} />{entity.name}<small>{{ student: "人物", college: "学院", place: "地点" }[entity.type]}</small></label>; })}</div> : <p>暂无可关联的校园档案。<Link href="/create/wiki">建立校园档案</Link></p>}</fieldset>
    <div className="event-actions"><button disabled={pending} type="submit" onClick={() => { if (intentRef.current) intentRef.current.value = "save"; }}>{pending ? "正在保存…" : event?.status === "published" ? "保存更新" : "保存草稿"}</button><button type="button" onClick={() => setPreview(!preview)} aria-expanded={preview}>预览时间线</button><button disabled={pending} className="button button-primary" type="submit" onClick={() => { if (intentRef.current) intentRef.current.value = "publish"; }}>{event?.status === "published" ? "更新公开档案" : "发布档案"}</button></div>
    {event && <p><Link href={`/create/event/${event.id}/preview`}>打开完整已保存预览 →</Link></p>}
    {preview && <section className="event-preview"><h2>时间线预览</h2><ol className="event-timeline">{nodes.map((node) => <li key={node.id}><time>{node.label}</time><div><h3>{node.title || "未填写节点标题"}</h3><p>{node.description}</p></div></li>)}</ol></section>}
  </form>;
}
