import Link from "next/link";
import type { getEvent } from "../queries";
import { supplementKinds } from "../schemas";
import type { WikiEntitySummary } from "../../wiki/types";
export function EventDetail({ archive, entities, creatorId, preview = false }: { archive: NonNullable<Awaited<ReturnType<typeof getEvent>>>; entities: WikiEntitySummary[]; creatorId?: string | null; preview?: boolean }) {
  const { event, nodes, supplements, creator, links } = archive;
  const related = entities.filter((entity) => links.some((link) => link.entity_id === entity.id && link.entity_type === entity.type));
  return <><nav className="event-crumb"><Link href="/events">校史事件</Link><span>/</span><span>{preview ? "档案预览" : "事件档案"}</span></nav>{preview && <p className="event-notice">已保存版本预览 · {event.status === "published" ? "公开档案" : "仅维护者可见"} <Link href={`/create/event/${event.id}`}>返回编辑</Link></p>}<header className="event-cover"><p className="archive-label">KONGTIAN UNIVERSITY / ARCHIVES</p><p className="event-date">{event.time_range || event.starts_on || "时间待考"}</p><h1>{event.title}</h1><p className="event-deck">{event.summary}</p><div className="event-cover-foot"><span>校史档案</span><span>{nodes.length} 个时间节点 · {supplements.length} 份补充资料</span></div></header><div className="event-reading-grid"><aside className="event-directory"><h2>本卷目录</h2><a href="#background">事件背景</a><a href="#timeline">事件经过</a><a href="#aftermath">后续影响</a><a href="#materials">补充资料</a><hr /><p>档案维护</p>{creator ? <Link href={`/creator/${creator.handle}`}>{creator.display_name}</Link> : <span>维护者暂不可用</span>}<p>修订版本 {event.version}</p>{creatorId === event.creator_id && <Link href={`/create/event/${event.id}`}>维护主档案 →</Link>}</aside><article className="event-reading"><section id="background"><p className="archive-label">BACKGROUND</p><h2>事件背景</h2><p>{event.causes || "暂无背景说明。"}</p></section><section id="timeline"><p className="archive-label">CHRONOLOGY</p><h2>事件经过</h2>{nodes.length ? <ol className="event-timeline">{nodes.map((node) => <li id={`node-${node.id}`} key={node.id}><time>{node.label}</time><div><h3>{node.title}</h3><p>{node.description}</p>{supplements.filter((supplement) => supplement.timeline_node_id === node.id).map((supplement) => <Link className="event-node-source" key={supplement.id} href={`/events/${event.id}/supplements/${supplement.id}`}>{supplementKinds[supplement.kind as keyof typeof supplementKinds] ?? "补充材料"} · {supplement.title} ↗</Link>)}</div></li>)}</ol> : <p>尚未编排时间节点。</p>}</section><section id="aftermath"><p className="archive-label">AFTERMATH</p><h2>后续影响</h2><p>{event.consequences || "暂无后续影响记录。"}</p></section>{related.length > 0 && <section><h2>关联档案</h2><div className="event-related">{related.map((entity) => <Link key={entity.id} href={`/wiki/${entity.type}/${encodeURIComponent(entity.slug)}`}>{entity.name} ↗</Link>)}</div></section>}<section id="materials"><div className="event-section-heading"><h2>补充资料</h2>{event.status === "published" && <Link href={`/create/event/${event.id}/supplement`}>提交补充资料 →</Link>}</div><p>以下材料独立署名，与主档案分开维护。</p>{supplements.length ? <ul className="event-materials">{supplements.map((supplement) => <li key={supplement.id}><span>{supplementKinds[supplement.kind as keyof typeof supplementKinds] ?? "补充材料"}</span><Link href={`/events/${event.id}/supplements/${supplement.id}`}>{supplement.title}</Link><time>{supplement.published_at?.slice(0, 10)}</time></li>)}</ul> : <p>本卷暂无公开补充资料。</p>}</section></article></div></>;
}
